### ISSUE TITLE
Add rotate left/right by constant amount

### ISSUE THREAD

**Issue by ZirconiumX** [nmigen/nmigen#339]
While it's not hard to roll your own in a function, it seems a bit more ergonomic to have `Value.rotate_{left,right}()` instead.

**Comment by whitequark** [comment]
Variable rotates or constant rotates?

**Comment by ZirconiumX** [comment]
Currently I only need constant rotates, but since you can build a rotate out of shifts, it shouldn't be difficult to also handle variable rotates.

**Comment by whitequark** [comment]
Constant rotates are easy and uncontroversial. Variable rotates not so much because if the LHS is not a power of 2 and the RHS can represent an absolute value larger than the length of LHS, you get a (possibly signed) modulus operator in the expansion and that's likely going to result in a nasty synthesized netlist.

**Comment by ZirconiumX** [comment]
Excellent point, I'd forgotten about that (and this is why I filed an issue first). I suppose it would have to be constant right hand side then.

**Comment by whitequark** [comment]
We can always extend it to varshifts later if someone comes up with a good way to handle this issue. So let's stick to constshifts for now.
