### ISSUE TITLE
submodules are allowed inside If blocks

### ISSUE THREAD

**Issue by jeanthom** [nmigen/nmigen#453]
This code looks sketchy to me, but it's currently being allowed by nMigen:

```python
from nmigen import *
from nmigen.cli import main

class MyElab(Elaboratable):
	def __init__(self):
		...

	def elaborate(self, platform):
		m = Module()

		return m

class Top(Elaboratable):
	def __init__(self):
		...

	def elaborate(self, platform):
		m = Module()

		with m.If(1):
			m.submodules += MyElab()

		return m

if __name__ == "__main__":
	top = Top()
	main(top)
```

**Comment by whitequark** [comment]
I'm not sure how confusing it is. I'm hesitant to forbid it outright because right now nMigen doesn't really have abstraction mechanisms besides submodules (i.e. there is no other construct similar to a "function"). If you had an actual bug caused by this I would be more inclined to make it an error, but so far I'm not aware of anyone hitting it.

**Comment by jeanthom** [comment]
I think it might be misleading to people who aren't familiar with HDL, thinking that they can add/remove elaboratables dynamically. By the way the generated RTLIL code looks correct (it will instantiate MyElab no matter the value of the condition).

**Comment by whitequark** [comment]
A lot of the things would be misleading to people who aren't familiar with HDL, and if we removed all of them, we wouldn't have any HDL at all. There needs to be a stronger argument, like someone actually hitting the problem.

**Comment by jeanthom** [comment]
No stronger argument ATM, I'm closing this issue.
